name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    name: Rust
    runs-on: ubuntu-22.04
    steps:
      # NOTE: rustup is installed by default

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Linux dependencies
        uses: ./.github/actions/install-linux-deps

      - name: Build
        run: cargo build -v

      - name: Test
        run: cargo test -v
